### ISSUE TITLE
Usage from Jest in Typescript

### ISSUE THREAD

**Issue by fluffynuts** [JamieMason/Jasmine-Matchers#100]
The documentation mentions adding the following to spec files to get the added matchers:
```typescript
import JasmineExpect from 'jasmine-expect';
```

However this does not work as expected with my combination of packages (should be current latest at time of writing):
- typescript: 2.8.3
- jest: 22.4.3
- jasmine-expect: 3.8.3

The snippet above gives the error: ".../node_modules/jasmine-expect/jasmine-matchers.d.ts is not a module". If I copy the .d.ts file into my repo root folder and change the namespace declaration from `jasmine` to `jest` and remove the `import` statement, then the problem goes away.

I'm not actually sure how this should be resolved, short of repeating the `declare namespace` for jasmine and jest. Personally, I think it's a little silly that jest is "rebranding" the jasmine namespace :/

**Comment by JamieMason** [comment]
There is a discussion somewhere I'm struggling to find but please try `import 'jasmine-expect';` in the meantime. See also https://github.com/JamieMason/expect-more/tree/master/packages/expect-more-jest which is a TypeScript rewrite of Jasmine-Matchers.

**Comment by fluffynuts** [comment]
I do use `import "jasmine-expect"`, but I also need to have the modified `.d.ts` file in my ts project otherwise I get grumbles whenever I attempt to use any of the added matchers.

I'll check out `expect-more-jest` in the morning -- thanks for the heads-up!

**Comment by JamieMason** [comment]
Great, I forgot I have this example too in development so have a look there too https://github.com/JamieMason/Jasmine-Matchers/tree/dev/examples/jasmine-typescript

**Comment by fluffynuts** [comment]
btw, `expect-more-jest` is working out fine for me -- though I'm not really stressing it yet; but a simple `npm install --save-dev expect-more-jest` and minor fixup in my spec files and I can remove my hacked `jest-matchers.d.ts`, so thanks (: 👍 👍

**Comment by JamieMason** [comment]
perfect 👍

**Comment by jelling** [comment]
Please update the homepage to include the example code provided by LarsImNetz, specifcally using `import "jasmine-expect";`. Also it is no longer necessary to get the @types since they're included.
