### ISSUE TITLE
toBeCloseToArray and toBeCloseToObject matches

### ISSUE THREAD

**Issue by manthey** [JamieMason/Jasmine-Matchers#101]
I have tests where I want to ensure an array is (a) an array of numbers, (b) the same length as an expected array, and (c) each pair of actual and expected array entries pass a `toBeCloseTo` test.  I would call this test `toBeCloseToArray`.

Similarly, I want to do the same thing with an object (`toBeCloseToObject`): the actual object (a) has exactly the same own properties as the expected object, (b) the value of each own property is a number, and (c) the value of a property of the actual and expected objects pass a `toBeCloseTo` test.

If this would be within the scope of the project, I would be happy to make a PR to add these.

**Comment by JamieMason** [comment]
Thanks a lot for the idea but I don't think many Developers would encounter this scenario. If there is more demand though I'm happy to reconsider.
