### ISSUE TITLE
Optional messages broken in 4.0.0

### ISSUE THREAD

**Issue by britvik** [JamieMason/Jasmine-Matchers#103]
After updating version from `3.8.4` to `4.0.0` some of my tests started failing with ridiculous messages like "**Expected true to be true**" or "**Expected false to be false**".

I noticed this happened for `toBeTrue` and `toBeFalse` matchers where I used `expectationFailOutput` message. E.g. `expect(someVar).toBeFalse('Some output message')`

After a bit of debugging I noticed that expectationFailOutput message is passed to the matcher (instead of actual boolean value from the expect function).

After I reverted back to `3.8.4` everything started working again.
I'm using jasmine `3.3.0`.

**Comment by JamieMason** [comment]
Thanks @britvik I will take a look.

**Comment by JamieMason** [comment]
Please try with [4.0.1](https://github.com/JamieMason/Jasmine-Matchers/blob/4.0.1/CHANGELOG.md#401-2019-01-12) and reopen this issue if the problem persists, thanks.

**Comment by britvik** [comment]
It works in 4.0.1. Thank you @JamieMason

**Comment by JamieMason** [comment]
Great! you're welcome.
