### ISSUE TITLE
Jasmine Matchers not working on Angular 7 and Karma

### ISSUE THREAD

**Issue by komyg** [JamieMason/Jasmine-Matchers#104]
Hi, 

I am trying to make the Jasmine Matchers to work with Angular 7 and Karma, but I am getting this error: `Uncaught TypeError: expect(...).toBeTrue is not a function` on my spec: `expect(result.loginSuccess).toBeTrue();`.

I followed the configuration steps on the readme:

- Installed the packages: `jasmine-expect`, `karma-jasmine-matchers` and `@types/jasmine-expect`.
- Added the jasmine matchers to the Karma config:
```
// Karma configuration file, see link for more information
// https://karma-runner.github.io/1.0/config/configuration-file.html

module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular-devkit/build-angular', 'jasmine-matchers'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular-devkit/build-angular/plugins/karma'),
      require('karma-jasmine-matchers')
    ],
    client: {
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    coverageIstanbulReporter: {
      dir: require('path').join(__dirname, '../coverage'),
      reports: ['html', 'lcovonly'],
      fixWebpackSourcePaths: true
    },
    reporters: ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['Chrome'],
    singleRun: false
  });
};
```
- Added the types to the `tsconfig.spec.json` file:
```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/spec",
    "module": "commonjs",
    "types": [
      "jasmine",
      "node",
      "jasmine-expect"
    ]
  },
  "files": [
    "test.ts",
    "polyfills.ts"
  ],
  "include": [
    "**/*.spec.ts",
    "**/*.d.ts"
  ]
}
```

But I still get an error. Could you help me?

Thanks,
Komyg

**Comment by komyg** [comment]
Hi Jamie,

I updated my packages (I had an older version o `karma-jasmine-matchers`, but I still get the same error: `Uncaught TypeError: expect(...).toBeTrue is not a function thrown`

Here are my packages:
```
    "jasmine-core": "^3.3.0",
    "jasmine-expect": "^4.0.1",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^3.1.4",
    "karma-chrome-launcher": "^2.2.0",
    "karma-cli": "^2.0.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "^2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "karma-jasmine-matchers": "^4.0.1",
```

Thanks,
Felipe

**Comment by komyg** [comment]
Hi Jamie,

I think I got it. I added an import to `jasmine-matcher` in my `tests.ts` file and the matchers were recognized.

Here is my full file:

```
// This file is required by karma.conf.js and loads recursively all the .spec and framework files

import 'zone.js/dist/zone-testing';
import { getTestBed } from '@angular/core/testing';
import {
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting
} from '@angular/platform-browser-dynamic/testing';
import 'jasmine-expect';

declare const require: any;

// First, initialize the Angular testing environment.
getTestBed().initTestEnvironment(
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting()
);
// Then we find all the tests.
const context = require.context('./', true, /\.spec\.ts$/);
// And load the modules.
context.keys().map(context);
```

Thanks for the help,
Felipe

**Comment by komyg** [comment]
I get both errors. My IDE (Visual Studio Code) complains that the `.toBetrue()` is not a function and at runtime I get the same error.

**Comment by JamieMason** [comment]
`.toBetrue()` is a typo, is it also that in your code? (should be `.toBeTrue()`)

**Comment by komyg** [comment]
No, I think I made the typo just in the message. This is the error message I got from Karma:

```
Chrome 71.0.3578 (Windows 10.0.0) ERROR
  {
    "message": "An error was thrown in afterAll\nUncaught TypeError: expect(...).toBeTrue is not a function thrown",
    "str": "An error was thrown in afterAll\nUncaught TypeError: expect(...).toBeTrue is not a function thrown"
  }
```

**Comment by JamieMason** [comment]
https://github.com/JamieMason/Jasmine-Matchers/blob/80d6e73763b2d8b9afb7d9ded9b0d020c0595a0b/examples/karma/karma.conf.js uses plain strings under `plugins` but you are using `require` calls, that is a difference I can tell with the working example at https://github.com/JamieMason/Jasmine-Matchers/issues/104#issuecomment-456004311 and your own that might be worth exploring – I would have a look at anything different between the working example and your own config, to see if any of those differences could be the cause of the problem 🤞

**Comment by komyg** [comment]
Hi Jamie,

I saw your file and tried to emulate it as best as I can (I removed the `require` statements and changed the order in which the plugins were declared, for example). However now I am experiencing a very strange behavior: sometimes my tests work and sometimes they fail with the `.toBeTrue() is not a function` error. 

Just now I ran Karma the first time and everything worked, then I ran a second time and I got this error, then I ran it a third time and I didn't get the `.toBeTrue() is not a function`, but I got a `.toBeFalse()`is not a function error, so it seems that Karma was able  to load the `.toBeTrue()` function successfully, but wasn't able to load the `.toBeFalse()`.

Do you have any idea why this might be happening?

As for the `import 'jasmine-expect';` statement, it was really required to get Karma running and it was not present when I ran the tests above, however it seems that this statement is important to get my IDE (Visual Studio Code) to see the additional matchers.

Thanks,
Felipe

**Comment by jecraig** [comment]
I had to add require at the top of my spec class to get this working.

`import 'jasmine-expect';  // <----- import here
import { SessionLogger } from './session-logger';

describe('SessionLogger', () => {
	it('should have initial value', () => {
		expect(SessionLogger.fetch()).toBeEmptyArray();
	});
});
`

**Comment by JamieMason** [comment]
Thanks all, I don't know what more to add than in my comment at https://github.com/JamieMason/Jasmine-Matchers/issues/104#issuecomment-456098236 that there is a working example available and that looking for differences between that and your own will serve as a guide towards getting your configuration working – sorry I can't add any more.
