### ISSUE TITLE
toContainSubstring

### ISSUE THREAD

**Issue by blockscoped** [JamieMason/Jasmine-Matchers#121]
## Matcher to check if a String or Array of Strings contains a given substring

The following matcher would be most useful in my tests:

```
expect('string to test against').toContainSubstring('test again')
expect('string to test against').not.toContainSubstring('test failed')
expect(['array', 'of', 'strings']).toContainSubstring('rings')
expect(['array', 'of', 'strings']).not.toContainSubstring('sting')
```

**Comment by blockscoped** [comment]
This could be one matcher or two separate matchers for the different input types.
```
toBeArrayOfStringsContainingSubstring()
```
Although that's a bit of a mouthful.

**Comment by blockscoped** [comment]
A companion matcher accepting a RegEx would also be very useful
```
expect('Date of birth 1983-12-22').toContainMatch(/(\d{4})-(\d{2})-(\d{2})/)
```

**Comment by JamieMason** [comment]
Hi @blockscoped, I think  Jasmine's [`toMatch`](https://jasmine.github.io/api/3.6/matchers.html#toMatch) should help a lot with this:

```js
expect('Date of birth 1983-12-22').toMatch(/(\d{4})-(\d{2})-(\d{2})/)
```

and [`toContain`](https://jasmine.github.io/api/3.6/matchers.html#toContain):

```js
expect('string to test against').toContain('test again')
```

In Jest I know you can do this, but Jasmine I'm not sure

```js
expect(['array', 'of', 'strings']).toEqual(expect.arrayContaining(expect.toMatch(/rings/)))
```

I hope this helps, thanks
