### ISSUE TITLE
Add support for withContext?

### ISSUE THREAD

**Issue by GCHQDeveloper911** [JamieMason/Jasmine-Matchers#123]
## Add support for Jasmine's 'withContext' function to allow custom messages with expectations

As of (I believe) jasmine 3, it is possible to do something like:
`expect(1).withContext('well that is never going to pass!').toEqual(2);`
to give more detailed output from the assertions.

I don't think jasmine-matchers currently supports withContext? This would be massively beneficial, as it would allow a jasmine based library we have to be used in a cucumber based environment, without modification to functions we have.

## Suggested Solution

Extract the withContext functionality from jasmine 3.

**Comment by devoto13** [comment]
@GCHQDeveloper911 Why do you think that `withContext()` is not supported? The message specified in `.withContext()` is printed when using `jasmine-expect` matchers for me.

Test code:

```
describe("Suite", function() {
  it("spec", function() {
    expect(1).withContext('well that is never going to pass!').toEqual(2);
    expect(true).withContext('Should never work!').toBeArray();
  });
});
```

Output:

```
Randomized with seed 13703
Started
F

Failures:
1) Suite spec
  Message:
    well that is never going to pass!: Expected 1 to equal 2.
  Stack:
    Error: well that is never going to pass!: Expected 1 to equal 2.
        at <Jasmine>
        at UserContext.<anonymous> (/Users/devoto13/Projects/trash/jasmine-emf/spec/support/index.spec.js:3:64)
        at <Jasmine>
  Message:
    Should never work!: Expected true to be array.
  Stack:
    Error: Should never work!: Expected true to be array.
        at <Jasmine>
        at UserContext.<anonymous> (/Users/devoto13/Projects/trash/jasmine-emf/spec/support/index.spec.js:4:52)
        at <Jasmine>

1 spec, 1 failure
Finished in 0.007 seconds
Randomized with seed 13703 (jasmine --random=true --seed=13703)
```

**Comment by JamieMason** [comment]
I think @devoto13 has answered this, thanks very much.
