### ISSUE TITLE
expect(object).toBePromise(); 

### ISSUE THREAD

**Issue by JamieMason** [JamieMason/Jasmine-Matchers#14]
http://wiki.commonjs.org/wiki/Promises

**Comment by jrencz** [comment]
@JamieMason one can use https://github.com/bvaughn/jasmine-es6-promise-matchers for vanilla js or https://github.com/bvaughn/jasmine-promise-matchers for Angular.

**Comment by JamieMason** [comment]
Thanks @jrencz yeah I agree, I think I'll close this.
