### ISSUE TITLE
instanceof checks may not be sufficient in node

### ISSUE THREAD

**Issue by tandrewnichols** [JamieMason/Jasmine-Matchers#21]
This is sort of an edge case, so I'd  understand if you didn't want to bother with it. I just added this package to our jasmine suite, and `.toBeFunction()` is reporting "Expected Function to be function." The reason is that we are using [sandboxed-module](https://github.com/felixge/node-sandboxed-module), which loads the subject under test using the `vm` module (in a separate context). `instanceof` doesn't seem to work when comparing objects from different contexts. E.g. (in our case):

```
// vm context - i.e. the subject-under-test
exports.a = function() {}
```

```
// test
expect(obj.a).toBeFunction() // fails because obj.a instanceof Function is false
```

For what's it worth, I don't blame you for this. The vm context instanceof problem is super annoying, and I've run into it before too. You might be able to do other checks in addition to `instanceof` to cover such cases. Something like `return this.actual isntanceof Function || typeof this.actual === 'function' || this.actual.apply`.

**Comment by JamieMason** [comment]
I think just `return typeof this.actual === 'function';` should be enough to cover this, do you agree or is more needed @tandrewnichols?

**Comment by tandrewnichols** [comment]
Yeah, I imagine that would be enough.
