### ISSUE TITLE
Suggestion: change repository structure so master is always the latest released version

### ISSUE THREAD

**Issue by jhuesos** [JamieMason/Jasmine-Matchers#22]
I would suggest something about how the repository is structured at this point and why I think it is better to do it in that way.

At this point, whenever people go the repo to check documentation, they can see the documentation of master, which is the next version that is going to be released at some point. But the problem is there will be breaking changes in the next version because there are new and old matchers remove.

What everyone needs to do now is to go to the repo, and select the 1.22.2 tag to see actually the documentation of the latest available version.

This issue could have been solved following more a git-flow approach, where master always contains the latest released version, and you develop the new one in a different branch (usually "develop"). And master is only upgraded once you release a new one.

With this new flow, everyone who land in the project main page, you will always see the right documentation.

Thanks

**Comment by vollyimnetz** [comment]
Hi, the file in the "dist" folder is still on version "1.22.3" (i think).

I have problems when get the files via bower. 
* Bower still uses the 1.22.3 version, which is fine as long as it is in beta. 
* However, if i try to get the files of the git-master via bower, i get the outdated "dist/jasmine-matchers.js".

Or is that intended?
