### ISSUE TITLE
expect(collection).toContainValues(array);

### ISSUE THREAD

**Issue by cryptoquick** [JamieMason/Jasmine-Matchers#26]
I'm looking for something like this:

```coffeescript
day_names = { mon: 'Monday', wed: 'Wednesday', tue: 'Tuesday' }
possible_day_names = ['Monday', 'Tuesday', 'Wednesday']
expect(_.values(day_names)).toBeInAnyOrder(possible_day_names)
```

I've found this pattern useful, when working over collections or objects that I know might come in a different order than what I might specify in the test. If the order is unimportant, the fact that I just have these items and only these items might be a good utility method to have on this library.

You'd implement it with the Lodash `_.xor` method, and determine if it's an empty array. If there are differences, maybe these should also be returned to expect and the user notified of the differences.

This is different than 'to have in any order', because _.xor isn't thinking about what's optional.

This plugin works great with `grunt-jasmine-bundle`, btw!

**Comment by JamieMason** [comment]
Thanks a lot for this @cryptoquick, does this deliver what you're describing?

```javascript
// Over Objects

expect({
    mon: 'Monday',
    wed: 'Wednesday',
    tue: 'Tuesday'
}).toContainValues([
    'Monday',
    'Tuesday',
    'Wednesday'
]);

// Over Arrays

expect([
    'Wednesday',
    'Monday',
    'Tuesday'
]).toContainValues([
    'Monday',
    'Tuesday',
    'Wednesday'
]);
```

**Comment by cryptoquick** [comment]
Yeah, that'd be pretty good!

**Comment by dkniffin** [comment]
Not sure if this should go here, or be it's own issue, but I'd also like to be able to test the order of arrays. So, for example:

````js
expect(['Wednesday','not-a-day', 'Monday'].toContainValuesInOrder(['Wednesday','Monday'])
````

**Comment by JamieMason** [comment]
Hey @cryptoquick, 
I fairly recently learned about [asymmetric matchers in Jasmine](https://github.com/JamieMason/Jasmine-Matchers#jasmines-default-asymmetric-matchers) – you should be able to achieve this using either `jasmine.arrayContaining(mixed);` or `jasmine.objectContaining(mixed);` 👍
