### ISSUE TITLE
isJasmineV1 always return true when using with protractor

### ISSUE THREAD

**Issue by pavelmigolinets** [JamieMason/Jasmine-Matchers#29]
Hi this boolean always return "true" when using with protractor, even when framework set as jasmine2 in protractor.conf.js. As result it always setting matchers as for version 1.x because if (isJasmineV1) always true.

**Comment by JamieMason** [comment]
Forgive me, is this not a bug with protractor? Is it augmenting Jasmine in some way? Or are there some other details also? Thanks a lot.

**Comment by pavelmigolinets** [comment]
not sure...they have some interactions with jasmine. But they didn't provide more options than jasmine does. I know only when you set framework as jasmine - isJasmineV1 = true, isJasmineV2 = false.But when you set framework jasmine2, both variables are true. I think you can fix this issue easily in a 5 minutes. as possible solution in jasmine-matchers.js : 
 var isJasmineV2 = typeof jasmine.addMatchers === 'function';
 if (isJasmineV2) {
     //do staff for jasmine v2.x
} else {
    //do staff for jasmine v1.x
}

in this way you won't care about other's problem, because your project will always works correct

Thanks in advance!

**Comment by JamieMason** [comment]
Sounds good, thanks @pavelmigolinets.
