### ISSUE TITLE
Add example project setups.

### ISSUE THREAD

**Issue by JamieMason** [JamieMason/Jasmine-Matchers#30]
Close and move https://github.com/JamieMason/karma-jasmine-matchers-example into an examples folder in this repo.

**Comment by arunprakashpj** [comment]
Is the issue still open ?

**Comment by JamieMason** [comment]
yes @arunprakashpj, just not had time yet to work on it.

**Comment by arunprakashpj** [comment]
Hi @JamieMason  , Shall i  move https://github.com/JamieMason/karma-jasmine-matchers-example into an examples folder in this repo ?

**Comment by JamieMason** [comment]
Hey @arunprakashpj.
Some of that will want to come over please, yes. What I was thinking of doing was something like;

```
.
└── examples
    ├── jasmine-cli
    ├── jasmine-node
    ├── jasmine-standalone
    ├── jest
    ├── karma
    └── protractor
```

Where each folder is a small working example project.

**Comment by arunprakashpj** [comment]
Okay. I will do it .
