### ISSUE TITLE
expect(something).toBeNaN();

### ISSUE THREAD

**Issue by MathRobin** [JamieMason/Jasmine-Matchers#34]
Hi !

Could be a great feature. Use global isNaN plus polyfills if Number.isNaN is not available (harmony feature)

**Comment by MathRobin** [comment]
Mozilla suggests this polyfill :

`
Number.isNaN = Number.isNaN || function(value) {
    return typeof value === "number" && value !== value;
}
`

https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Number/isNaN

**Comment by JamieMason** [comment]
Hey, always open to ideas. Do you have an example test you can show me that you'd hope to refactor with this new matcher? Thanks man.

**Comment by MathRobin** [comment]
Yes of course

`expect(condNode.configure({
     condition : NaN
})).not.toBeDefined();
if(Number.isNaN(condNode.condition)) {
expect(true).toBeTruthy();
} else {
expect(false).toBeTruthy();
}`

can become

`expect(condNode.configure({
     condition : NaN
})).not.toBeDefined();
expect(condNode.condition).toBeNaN();`

**Comment by MathRobin** [comment]
I'm coding a PR

**Comment by JamieMason** [comment]
Thanks again for this @MathRobin.

For the moment, unfortunately I don't think this kind of thing is encountered often enough by enough developers to warrant adding to the library. I also worry about confusion being introduced about which of the following to choose;

```javascript
expect(value).toBeNumber();
expect(value).not.toBeNumber();
expect(value).toBeNaN();
expect(value).not.toBeNaN();
```

I appreciate your interest and effort but on current information I can't add this, sorry.
