### ISSUE TITLE
require('jasmine-expect') API can only register watchers once

### ISSUE THREAD

**Issue by michael42** [JamieMason/Jasmine-Matchers#36]
We're trying to use jasmine-expect to test a node.js application using gulp-jasmine. The current `require('jasmine-expect')` API isn't sufficient for that use case, since it only registers the matchers once. When the watcher runs the tests a second time, the require() result is already cached and the matchers aren't registered.

A function that registers the matchers when called would solve this issue. Not sure how to integrate it without breaking backwards compatibility or registering the matchers multiple times, though.

**Comment by JamieMason** [comment]
Thanks for this @michael42.

Integration with Node is currently the most awkward aspect of this project. I agree that some kind of method is needed such as `require('jasmine-expect').register()` (or similar) to get around this problem.

**Comment by JamieMason** [comment]
/cc to users who've opened issues on this project before, a question for you. How do you tend to include Jasmine Matchers on a Node.js project? I'm trying to think of what might be the best way to do it — and I'm pretty sure it will require an API change.

Thanks.

@Hemins @JessicaSachs @MathRobin @PaulTondeur @RALifeCoach @alecxe @anisylen @atruskie @cryptoquick @endorama @jasonjohnson115 @jelinson @jhuesos @jrencz @message @michael42 @mohit-excelindia @mrozbarry @mull @pavelmigolinets @rkawala @tandrewnichols @xuxiankun

**Comment by mull** [comment]
We're only including it once in our of our jest specs by simply importing it. Sorry I can't be of more help :/

**Comment by anisylen** [comment]
Same as @mull. Include it once within our Jasmine specs and let it rip.

**Comment by JamieMason** [comment]
Thanks @mull @anisylen. I had thought that just including `require('jasmine-expect')` at the very start of your spec was all that was needed to include this in node, but I could see how it could be possible that the behaviour @michael42 describes could happen.

Could it be that this has been fixed since it was opened? @michael42 can you confirm?

Thanks.

**Comment by PaulTondeur** [comment]
I can confirm the include as @mull and @anisylen are describing.

**Comment by mrozbarry** [comment]
We are including it in a helper file, and our setup looks like this:

spec/support/jasmine.json:

```json
{
  "spec_dir": "spec",
  "spec_files": [
    "**/*.spec.js"
  ],
  "helpers": [
    "helpers/*.js"
  ]
}
```

spec/helpers/extra.js:

```js
// ...
require('jasmine-expect');
// ...
```

**Comment by JamieMason** [comment]
Thanks all, ok I _think_ this is working then and can be closed.

**Comment by michaeljota** [comment]
Hi! You should post this on the readme.md. This is like a how-to-use with gulp-jasmine.

Thanks! :+1:
