### ISSUE TITLE
Move matchers to separate file?

### ISSUE THREAD

**Issue by message** [JamieMason/Jasmine-Matchers#41]
Jest is based on Jasmine, i want to extend Jest with your matchers, but `index.js` fires `lib/factory`. Can you please move matchers to separate `matchers.js` file, so i can access matchers collection without firing `factory`?

**Comment by JamieMason** [comment]
Hi Dmitry, I'd be happy to do this but could you add a little more detail on what is happening? I get the general idea but am missing something I think.

**Comment by message** [comment]
I rushed a little bit, sorry. `require("jasmine-expect");` works fine Jest without any modifications

**Comment by JamieMason** [comment]
No problem at all. Actually I planned to try Jest soon, is that require literally all that's needed to use these matchers? I'd have thought there'd be something more needed to port them over, but that's great if not.

**Comment by message** [comment]
**test.js**
```js
var gulp = require("gulp");
var jest = require("gulp-jest-iojs"); // I'm using Node v4.1 and latest Jest

gulp.task("test", function() {
	var isDevelopment = (process.env.NODE_ENV === "development");
	return gulp.src("./src", {read: false})
		.pipe(jest({
			scriptPreprocessor: __dirname + "../../../node_modules/babel-jest",
			setupTestFrameworkScriptFile: __dirname + "../../utils/jestSetup.js",
			testFileExtensions: ["test.js"],
			collectCoverage: ! isDevelopment,
			unmockedModulePathPatterns: ["classnames", "immutable"]
		})).on("error", function(error) {
			this.emit("end"); // Keep gulp from hanging on this task
			if (! isDevelopment) process.exit(1); // Exit with error when in production
		});
});
```
**jestSetup.js**
```
require("jasmine-expect");
```

**Comment by JamieMason** [comment]
Cool, thanks a lot for the info.
