### ISSUE TITLE
.toImplement does not properly check type

### ISSUE THREAD

**Issue by mrozbarry** [JamieMason/Jasmine-Matchers#42]
The example for .toImplement() uses a hash where the key must exist, and implies that the value is the type the actual value should be.  This method does not seem to test for individual types off the actual object, and fails when we build a mock object that is exactly what the test expects, ie:

This will pass:

```
expect({
  foo: 'bar',
  baz: 123,
  foobarbaz: [1, 2, 3]
}).toImplement({
  foo: String,
  baz: Number,
  foobarbaz: Array
})
```

but so will this:

```
expect({
  foo: 'bar',
  baz: '123',
  foobarbaz: [1, 2, 3]
}).toImplement({
  foo: String,
  baz: Number,
  foobarbaz: Array
})
```

Even though `baz` is a string but is expected to be a number.

If this is just checking for the existance of all attributes, why not have toImplement accept an array of the hash keys?

**Comment by JamieMason** [comment]
Yes absolutely, I need to finish this so it uses the types. 

Thanks a lot.
