### ISSUE TITLE
expect(object).toBeSet() & expect(object).toBeSetOf(String)

### ISSUE THREAD

**Issue by jrencz** [JamieMason/Jasmine-Matchers#43]
String is an example. It should be able to iterate over the `Set` and check if all its elements match the given type.

**Comment by JamieMason** [comment]
Thanks @jrencz, would you mind writing some example tests in here? What some key specs would look like using Jasmine-Matchers with this implemented.

**Comment by jrencz** [comment]
`.toBeEmptySet` would be useful as well

**Comment by jrencz** [comment]
@JamieMason do you have any way to handle host objects that are not present everywhere already defined in the project?

It's easy to write a polyfill but I need to include Symbol polyfill to implement `Symbol.toStringTag` properly.

**Comment by JamieMason** [comment]
I've not used `Symbol` before @jrencz, can you explain this some more?

**Comment by jrencz** [comment]
@JamieMason `Symbol` is a way to define most of those "magical" JS features present before ES2015. One of those is the host objects ability to define how Object#toString works when an object is passed to it. `Set` has `Set[Symbol.toStringTag]` similar to `function () { return '[Object Set]'; }`

For now I just opted out of testing in browsers without Set implemented, but I'd like you to hint me what to do if you already have a plan for such situations.

**Comment by jrencz** [comment]
and `Symbol.iterator` would be useful to be able to implement `toBeSetOf`. But then I'm going to need `forOf` loop anyway (in the most simple approach)

**Comment by JamieMason** [comment]
Thanks again for raising this @jrencz but I've decided not to add matchers for `Set` etc. A new project such as jasmine-set-matchers could be useful to people though if you decide to take it on.

**Comment by jrencz** [comment]
ok
