### ISSUE TITLE
expect(object).toBeSymbol() & toBeWellKnownSymbol() & toBeCustomSymbol() & toBeSymbolFor(string)

### ISSUE THREAD

**Issue by jrencz** [JamieMason/Jasmine-Matchers#45]
It's related to #43 - Symbols may be matched as well

`toBeWellKnownSymbol` should pass [well-known Symbols](https://developer.mozilla.org/pl/docs/Web/JavaScript/Reference/Global_Objects/Symbol#Well-known_symbols) and `toBeCustomSymbol` (any hint on a better name?) should fail then a well-known symbol is passed.
Well-known symbols exist as properties on `Symbol` host object.

**Comment by JamieMason** [comment]
Thanks @jrencz, I'd need a lot of input from you on this as I've not used Symbols.

**Comment by JamieMason** [comment]
Thanks again for raising this @jrencz but I've decided not to add matchers for `Set` etc. A new project such as jasmine-set-matchers could be useful to people though if you decide to take it on.
