### ISSUE TITLE
Documentation should show what matchers are in beta

### ISSUE THREAD

**Issue by anisylen** [JamieMason/Jasmine-Matchers#47]
Currently, running the recommended npm or bower installation methods installs v1.22.3. This does not seem to have a lot of the methods as shown in the documentation.

If possible please specify what features are there in beta until a full release of 2.0 or explicitly add the version within the installation instructions.

**Comment by JamieMason** [comment]
Hey @anisylen, thanks for raising this. 

Please see here the [README for Jasmine-Matchers 1.22.3](https://github.com/JamieMason/Jasmine-Matchers/tree/d441ec64e3a4cec39d5b7d86981cbca94cb33dce).

**Comment by anisylen** [comment]
I just installed the beta version since that has a lot of the matchers that I need. Thanks!

**Comment by JamieMason** [comment]
Great, thanks @anisylen
