### ISSUE TITLE
Add .toBeValidDate()

### ISSUE THREAD

**Issue by PaulTondeur** [JamieMason/Jasmine-Matchers#49]
I would expect that this test would fail for invalid dates: 
`expect(new Date("invalid")).toBeDate()`

Or that there would be a test like:
`expect(new Date("invalid")).toBeValidDate()`

Workaround could be:
`expect(new Date("invalid")).toBeAfter(new Date(0));`

**Comment by JamieMason** [comment]
Thanks for this @PaulTondeur, I'm not sure yet how to approach this so will think it over for a while.

**Comment by JamieMason** [comment]
I ran a [poll on Twitter](https://twitter.com/fold_left/status/794092987064131584) to try and help gauge Developers' expectations and it seems people are fairly split. Here's what I think is the best way to accommodate both sides of the argument and avoid breaking changes. 

* Keep `toBeDate` working the same as it does now. This will avoid breaking changes and upsetting users that find the way it works now to be correct.
* Add `toBeValidDate`, as you suggest, which works the way the other half of Developers expect.

**Comment by jacobwarduk** [comment]
https://github.com/JamieMason/Jasmine-Matchers/pull/67 adds the `toBeValidDate` matcher.

**Comment by PaulTondeur** [comment]
Thanks a lot for picking it up and I agree with your conclusions to solve it this way!
