### ISSUE TITLE
Deprecate .toImplement

### ISSUE THREAD

**Issue by atruskie** [JamieMason/Jasmine-Matchers#53]
Hi,

Not sure if these are intended features of `.toImplement` or not but I find the following behaviours (introduced in #42 / 866e832 ) to be counterintuitive:

## Testing if an object implements a field that is `null`/`undefined`

```
var actual = { fieldA: 'a value', fieldB: null };
var expected = { fieldA: String, fieldB: null };
expect(actual).toImplement(expected);
```

Produces:
```
Chrome 48.0.2564 (Windows 10 0.0.0) The bawResource service test FAILED
        TypeError: Cannot read property 'constructor' of null
            at featuresAll ([OMITTED]/vendor/jasmine-expect/dist/jasmine-matchers.js:1723:62)
            at toImplement ([OMITTED]/vendor/jasmine-expect/dist/jasmine-matchers.js:1718:17)
            at compare ([OMITTED]/vendor/jasmine-expect/dist/jasmine-matchers.js:374:38)
            at Object.<anonymous> ([OMITTED]/es6/src/components/services/bawResource.spec.js:55:24 <- ../../../../src/components/services/bawResource.spec.js:55:23)
```

### Expected result
The test case to pass . Even if not intended to pass, the exception breaks the test reporter. The matcher should return `false` and not throw.

It seems valid to me that an object be required to have a field even if its value is `null` - as `null` is valid value. The argument for `undefined` is a little less convincing but I'd personally still expect it to work. 

## Testing if a _function_ object implements an interface:

```
        var actual = function noop(){};
        actual.extraField = "some useful property";
        actual.extraFunction = function noop2() {};

        var expected = { extraField: String, extraFunction: Function };
        expect(actual).toImplement(expected);
```

Produces:
```
Chrome 48.0.2564 (Windows 10 0.0.0) The bawResource service test FAILED
        Expected Function to implement Object({ extraField: Function, extraFunction: Function }).
            at Object.<anonymous> ([OMITTED]/es6/src/components/services/bawResource.spec.js:58:24 <- ../../../../src/components/services/bawResource.spec.js:58:23)
```

### Expected
The test case to pass. A function is a valid object just like any other. 

Are these properties intended behaviour?

**Comment by JamieMason** [comment]
Thanks @atruskie — completely agree, these are all valid points.

**Comment by JamieMason** [comment]
`toImplement` will be deprecated and replaced with #55.

**Comment by atruskie** [comment]
Thanks for the heads up - new API looks good.

**Comment by JamieMason** [comment]
Deprecated in [3.0.1](https://github.com/JamieMason/Jasmine-Matchers/releases/tag/3.0.1).
