### ISSUE TITLE
expect(floatNumber).toBeNear(number, epsilon)

### ISSUE THREAD

**Issue by Nolanus** [JamieMason/Jasmine-Matchers#58]
Compare a given value numerically to be in the range of `number-epsilon` and `number+epsilon`. Thus `epsilon` specifies the maximum tolerance the compared value is allowed to vary.

Example

```
expect(4.23223432434).toBeNear(4, 0.25); // success
expect(4.23223432434).toBeNear(4, 0.2); // failure
```

Implementation

Could internally use  the "toBeWithinRange" matcher, but the above is much nicer to write if you're not targeting a specific range, but just a value and allow some wobbling.

**Comment by JamieMason** [comment]
Thank you for this, at what times would you use either this or Jasmine's toBeCloseTo please?

**Comment by Nolanus** [comment]
The second parameter of Jasmine's `toBeCloseTo` is non-linear. Especially when comparing integer values a lot of tweaking is required to get the expected "tolerance area":

```
expect(22).toBeNear(20, 2); // success
expect(22).toBeNear(20, 1); // failure
expect(22).toBeCloseTo(20, ??); // What to choose as "precision" parameter?
```

**Comment by JamieMason** [comment]
Thanks @Nolanus, do I understand correctly that

```js
expect(22).toBeNear(20, 2);
```

is equivalent to

```js
expect(22).toBeWithinRange(18, 22);
```

**Comment by Nolanus** [comment]
Hi @JamieMason,
that's correct.

Just realized my initial example was wrong, just fixed that.

**Comment by jacobwarduk** [comment]
https://github.com/JamieMason/Jasmine-Matchers/pull/68 adds the `toBeNear()` matcher.
