### ISSUE TITLE
toBeSafeInteger

### ISSUE THREAD

**Issue by jacobwarduk** [JamieMason/Jasmine-Matchers#73]
A matcher worthy of inclusion?

**Comment by JamieMason** [comment]
Sorry for the delay @jacobwarduk.

I don't know if safe integers are that commonly used? I'm open to persuasion but I don't think it would be worth it. 

Note: it also looks like the following may be added to JS;

> ```js
> Number.isSafeInteger
> Number.MAX_SAFE_INTEGER
> Number.MIN_SAFE_INTEGER
> ```
> – http://2ality.com/2013/10/safe-integers.html

Thanks all the same, really appreciate your ideas.
