### ISSUE TITLE
Jest installation not working

### ISSUE THREAD

**Issue by mandysimon88** [JamieMason/Jasmine-Matchers#75]
Followed directions for the Jest installation, but I get:
```
TypeError: this.addMatchers is not a function
      at Object.<anonymous> (node_modules/jasmine-matchers/src/toThrow.js:2:8)
```

**Comment by JamieMason** [comment]
Hi, please give this working example a try https://github.com/JamieMason/Jasmine-Matchers/tree/master/examples/jest. Hope this helps, thanks.

**Comment by mandysimon88** [comment]
Finally realized the problem-- you have to add:
```
"setupTestFrameworkScriptFile": "<rootDir>/node_modules/jasmine-expect/index.js"
```

Could drop that into the README. We already have that option assigned to `jest-enzyme`, so it looks like we'd need to write our own script file to call first jest-enzyme and then jasmine-expect... which makes it kind of not worth it to us.

Would have been helpful to have that in the README because I would have realized that before changing my tests. ;-)

**Comment by JamieMason** [comment]
That's not something I've encountered before so, thank you for sharing! 🎉
