### ISSUE TITLE
not working with Jest@20

### ISSUE THREAD

**Issue by orangecms** [JamieMason/Jasmine-Matchers#79]
With jest@20, steps using the additional matchers raise the following error:
```TypeError: Cannot read property 'buildFailureMessage' of undefined```

I'm not sure about the cause. What I found out so far is that they replace Jasmine with jest-circus in https://github.com/facebook/jest/pull/3668/files.

I think they want to use `extpect.extend` now instead of `addMatchers`: https://facebook.github.io/jest/docs/expect.html#expectextendmatchers

**Comment by JamieMason** [comment]
Which version of Jasmine-Matchers are you using please? 

It should be using `expect.extend` if you are using Jest (see [add-matchers/src/create-register.js#L11-L19](https://github.com/JamieMason/add-matchers/blob/master/src/create-register.js#L11-L19)) but it may be that something else has changed in Jest 20.

**Comment by JamieMason** [comment]
`buildFailureMessage ` is only referenced in [the Jasmine v2 adapter](https://github.com/JamieMason/add-matchers/search?utf8=%E2%9C%93&q=buildFailureMessage&type=) – you don't have Jasmine loaded as well somehow do you?

**Comment by orangecms** [comment]
This is so embarrassing... I was on the latest v2, so I entirely missed the major version bump to v3. Upgrading fixed the issue. Sorry for bothering you and thank you so much!

**Comment by JamieMason** [comment]
You're welcome, don't worry about it 👍
