### ISSUE TITLE
Improve message produced by toHaveMethod

### ISSUE THREAD

**Issue by JamieMason** [JamieMason/Jasmine-Matchers#84]
```
expected member "isLoading" of {} to have method
```

**Comment by jacobwarduk** [comment]
What kind of message were you thinking?

**Comment by JamieMason** [comment]
hey @jacobwarduk, to follow the name of the matcher I think the message should be `expected {} to have method "isLoading"`.

I think this used to work at one time but has since had a regression, we have solid tests for the behaviour of the matchers but not for the messages.
