### ISSUE TITLE
expect(object).toBe[Non]EmptyObject();

### ISSUE THREAD

**Issue by JamieMason** [JamieMason/Jasmine-Matchers#9]
1. Assert value is an Object with no instance members.
1. Assert value is an Object with at least one instance member.

**Comment by mpiasta-ca** [comment]
Is this going to be added sometime?

**Comment by JamieMason** [comment]
Hi @mpiasta-ca, it's in [develop](https://github.com/JamieMason/Jasmine-Matchers/tree/develop) at the moment.

**Comment by JamieMason** [comment]
Released in [2.0.0-beta1](https://github.com/JamieMason/Jasmine-Matchers/releases/tag/2.0.0-beta1).
