### ISSUE TITLE
TypeScript error: All declarations of 'Matchers' must have identical type parameters.

### ISSUE THREAD

**Issue by shaungrady** [JamieMason/Jasmine-Matchers#91]
I'm seeing this problem with the following versions:
```
    "@types/jasmine": "^2.5.53",
    "jasmine-expect": "^3.7.1"
```

```
[at-loader] ./node_modules/@types/jasmine/index.d.ts:404:15 
    TS2428: All declarations of 'Matchers' must have identical type parameters. 

[at-loader] ./node_modules/jasmine-expect/jasmine-matchers.d.ts:2:13 
    TS2428: All declarations of 'Matchers' must have identical type parameters. 
```

From `@types/jasmine`:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jasmine/index.d.ts#L404

I edited this package (`jasmine-matchers`) locally to match `@types/jasmine`, and the errors go away. Just modify [`jasmine-matchers.d.ts:2`](https://github.com/JamieMason/Jasmine-Matchers/blob/master/jasmine-matchers.d.ts#L2) to 

``` typescript
  interface Matchers<T> {
```

... and everything works.

**Comment by JamieMason** [comment]
This should hopefully be address in [3.8.3](https://github.com/JamieMason/Jasmine-Matchers/blob/master/CHANGELOG.md#383-2018-01-29). 
Please give that a try and let us know via a comment or by closing the issue, thanks.
