### ISSUE TITLE
How to access Jasmine when it is an AMD module instead of a global?

### ISSUE THREAD

**Issue by sorin-postelnicu** [JamieMason/Jasmine-Matchers#99]
Dear all,

In our project we are using jasmine with requirejs, and now we are trying to add Jasmine-Matchers (v3.8.3), but we get the following error:

> Uncaught Error: jasmine-expect cannot find jest, jasmine v2.x, or jasmine v1.x
at createRegister ( add-matchers.js:63 )

The configuration of Jasmine by using RequireJS is done like this: https://gist.github.com/sorin-postelnicu/02ca666b8ac17adc5e614db5dc9730c5

But when we run this simple example from the gist, we get the error mentioned above.

It looks like jasmine-require is trying to find jasmine in the global object, instead of integrating with requirejs.

How would you advise us to configure it, in order to integrate with the setup we created with requirejs?

**Comment by JamieMason** [comment]
Hi @sorin-postelnicu,
I honestly don't know unfortunately, Jasmine is most often run in global scope and this is what this library expects. There may be a way but this is not a situation I have faced yet, sorry I have not been able to be more helpful here.
